# fly.toml app configuration file generated for jibni-backend
app = 'jibni-backend'
primary_region = 'sjc'

[build]
  builder = 'nixpacks'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = '15s'
  method = 'GET'
  path = '/health'
  protocol = 'http'
  timeout = '2s'
  tls_skip_verify = false

[deploy]
  release_command = 'npm run build'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = 'jibni_data'
  destination = '/data'
