export const wilayas: Record<number, string> = {
  1: "Adrar",
  2: "Chlef",
  3: "Laghouat",
  4: "Oum El Bouaghi",
  5: "Batna",
  6: "Béjaïa",
  7: "Biskra",
  8: "Béchar",
  9: "Blida",
  10: "Bouïra",
  11: "Tamanrasset",
  12: "Tébessa",
  13: "Tlemcen",
  14: "Tiaret",
  15: "Tizi Ouzou",
  16: "Alger",
  17: "Djelfa",
  18: "Jijel",
  19: "Sétif",
  20: "Saïda",
  21: "Skikda",
  22: "Sidi Bel Abbès",
  23: "Annaba",
  24: "Guelma",
  25: "Constantine",
  26: "Médéa",
  27: "Mostaganem",
  28: "Msila",
  29: "Mascara",
  30: "Ouargla",
  31: "Oran",
  32: "El Bayadh",
  33: "Illizi",
  34: "Bordj Bou Arréridj",
  35: "Boumerdès",
  36: "El Tarf",
  37: "Tindouf",
  38: "Tissemsilt",
  39: "El Oued",
  40: "Khenchela",
  41: "Souk Ahras",
  42: "Tipaza",
  43: "Mila",
  44: "Aïn Defla",
  45: "Naâma",
  46: "Aïn Témouchent",
  47: "Ghardaïa",
  48: "Relizane",
  49: "El M'Ghair",
  50: "El Meniaa",
  51: "Ouled Djellal",
  52: "Bordj Baji Mokhtar",
  53: "Béni Abbès",
  54: "Timimoun",
  55: "Touggourt",
  56: "Djanet",
  57: "In Salah",
  58: "In Guezzam",
};

export const wilayasFR: Record<number, string> = {
  1: "Adrar",
  2: "Chlef",
  3: "Laghouat",
  4: "Oum El Bouaghi",
  5: "Batna",
  6: "Béjaïa",
  7: "Biskra",
  8: "Béchar",
  9: "Blida",
  10: "Bouïra",
  11: "Tamanrasset",
  12: "Tébessa",
  13: "Tlemcen",
  14: "Tiaret",
  15: "Tizi Ouzou",
  16: "Alger",
  17: "Djelfa",
  18: "Jijel",
  19: "Sétif",
  20: "Saïda",
  21: "Skikda",
  22: "Sidi Bel Abbès",
  23: "Annaba",
  24: "Guelma",
  25: "Constantine",
  26: "Médéa",
  27: "Mostaganem",
  28: "Msila",
  29: "Mascara",
  30: "Ouargla",
  31: "Oran",
  32: "El Bayadh",
  33: "Illizi",
  34: "Bordj Bou Arréridj",
  35: "Boumerdès",
  36: "El Tarf",
  37: "Tindouf",
  38: "Tissemsilt",
  39: "El Oued",
  40: "Khenchela",
  41: "Souk Ahras",
  42: "Tipaza",
  43: "Mila",
  44: "Aïn Defla",
  45: "Naâma",
  46: "Aïn Témouchent",
  47: "Ghardaïa",
  48: "Relizane",
  49: "El M'Ghair",
  50: "El Meniaa",
  51: "Ouled Djellal",
  52: "Bordj Baji Mokhtar",
  53: "Béni Abbès",
  54: "Timimoun",
  55: "Touggourt",
  56: "Djanet",
  57: "In Salah",
  58: "In Guezzam",
};

export const wilayasAR: Record<number, string> = {
  1: "أدرار",
  2: "شلف",
  3: "الأغواط",
  4: "أم البواقي",
  5: "باتنة",
  6: " بجاية",
  7: "بسكرة",
  8: "بشار",
  9: "البليدة",
  10: "البويرة",
  11: "تمنراست",
  12: "تبسة",
  13: "تلمسان",
  14: "تيارت",
  15: "تيزي وزو",
  16: "الجزائر",
  17: "الجلفة",
  18: "جيجل",
  19: "سطيف",
  20: "سعيدة",
  21: "سكيكدة",
  22: "سيدي بلعباس",
  23: "عنابة",
  24: "قالمة",
  25: "قسنطينة",
  26: "مديونة",
  27: "مستغانم",
  28: "مسيلة",
  29: "معسكر",
  30: "ورقلة",
  31: "وهران",
  32: "البيض",
  33: "إليزي",
  34: "برج بوعريريج",
  35: "بومرداس",
  36: "الطارف",
  37: "تيندوف",
  38: "تيسمسيلت",
  39: "الوادي",
  40: "خنشلة",
  41: " سوق أهراس",
  42: "تيبازة",
  43: "ميلة",
  44: "عين الدفلى",
  45: "النعامة",
  46: "عين تموشنت",
  47: "غرداية",
  48: "غليزان",
  49: "المغير",
  50: "المنيعة",
  51: "أولاد جلال",
  52: "برج باجي مختار",
  53: "بيني عباس",
  54: "تيميمون",
  55: "تقرت",
  56: "جانت",
  57: "إن صالح",
  58: "إن قزام",
};

export const getWilayaName = (id: number, language: 'fr' | 'en' | 'ar'): string => {
  if (language === 'ar') {
    return wilayasAR[id] || wilayas[id];
  }
  return wilayas[id] || wilayasFR[id] || String(id);
};
